### ISSUE TITLE
Frage zu deiner Lösung 

### ISSUE THREAD

**Issue by UliD-zz** [zivillian/heidelberg-1p3p#4]
Lese deinen Beitrag mit großem Interesse weil ich gleiche Problematik habe. Gibt es mit der Heidelberg keine Probleme wenn du bei der Umschaltung auch die L1 Phase anschaltest? Damit wäre die Wallbox ja komplett abgeschaltet und müsste komplett neu starten.

**Comment by zivillian** [comment]
Ich habe das in der Form seit dem Frühjahr im Einsatz und bisher keine Probleme. Der Neustart der Wallbox dauert ca. 3 Sekunden. Der Mikrocontroller wartet bis die Wallbox wieder antwortet und liefert so lange die gecachten Register, so dass auch evcc kein Problem damit hat.

Erst heute wurde wieder mehrfach zwischen 1 und 3-phasig umgeschaltet - je nachdem wie die Sonne gerade steht.

**Comment by UliD-zz** [comment]
Danke für die schnelle Antwort. Bin gerade unterwegs und kann nicht ausführlicher antworten, hab sicher noch fragen, darf ich dich dann nochmal ansprechen?Sent from mobile deviceAm 17.09.2023 um 20:05 schrieb zivillian ***@***.***>:﻿
Ich habe das in der Form seit dem Frühjahr im Einsatz und bisher keine Probleme. Der Neustart der Wallbox dauert ca. 3 Sekunden. Der Mikrocontroller wartet bis die Wallbox wieder antwortet und liefert so lange die gecachten Register, so dass auch evcc kein Problem damit hat.
Erst heute wurde wieder mehrfach zwischen 1 und 3-phasig umgeschaltet - je nachdem wie die Sonne gerade steht.

**Comment by zivillian** [comment]
Klar, ich freue mich, wenn das auch anderen hilft - vielleicht schaffen wir es ja irgendwann, dass es ein Standard Feature von evcc wird.
