### ISSUE TITLE
Verbindung EVCC, Dingtian DT-R002 Board und Wallbox

### ISSUE THREAD

**Issue by kon1992** [zivillian/heidelberg-1p3p#6]
Hi,

ich finde die Lösung sehr interessant. Allerdings ist mir ein Punkt noch nicht ganz klar.
Wie ist denn die Verbindung von EVCC zum Dingtian DT Board? Geht das aktuell über WLAN? Auf dem Foto sehe ich nur ein Bus/Netzwerkkabel. Ich vermute das geht dann nur zur Wallbox.

Grüße
Konrad

**Comment by zivillian** [comment]
Ja, aktuell läuft das über WLAN.

**Comment by kon1992** [comment]
Danke! Dann würde ich mich issue #5 anschließen. Wlan ist im Keller/TG oft nicht verfügbar und eine LAN Verbindung wäre da praktischer.
