### ISSUE TITLE
Anleitung zum flashen

### ISSUE THREAD

**Issue by fnsolar** [zivillian/heidelberg-1p3p#7]
Da die Software genau das macht, was ich für meine Heidelberg-Box suche, hatte ich kurzerhand die Teile bestellt. Nun stelle ich fest, dass ich leider keine Ahnung habe, wie ich dem ESP32 die Firmware aufspiele. Habe das bisher nur mit Sonoff-WLAN-Boards und Arduinos gemacht. 
Gibt es irgendwo eine Anleitung dazu? Für einen Hinweis, wo ich soetwas finde, wäre ich sehr dankbar!

**Comment by jetronic18s** [comment]
Hallo, hast du das ESP32 Board mit dem Zusatz "Dev Board" gekauft?

**Comment by fnsolar** [comment]
Ja, habe ich. Es geht mir um den Ablauf des flashens, da ich es lange nicht mehr gemacht habe. Ging damals nur über einen USB-Seriell-Adapter, der aber hier nicht mehr erforderlich zu sein scheint, da es ja bereits ein GUI gibt. Habe dort jedoch noch nicht den entsprechenden Menüpunkt gefunden. 
Ferner ist mir nicht klar, ob das Programm bereits in kompilierter Form vorliegt oder ob ich es selbst noch kompilieren muss (und wenn ja, womit). 
Wäre für jegliche Hinweise dankbar und im Gegenzug bereit, meine "Gelerntes" in einer kurzen Anleitung zusammen zu fassen, um das Projekt mehr Menschen zugänglich zu machen.

**Comment by zivillian** [comment]
Initial habe ich das immer mit VS Code und dem Platformio Plugin und einem USB-Seriell Adapter geflasht. Anschließend können die Updates über das Webinterface hochgeladen werden - da können dann auch einfach die Binaries aus dem Release oder den Github Actions genutzt werden.

Die PIN Belegung für den Seriellen Port sieht man [hier](https://github.com/dtlzp/relay_dev_demo/blob/main/gpio_pinout/debug_port_2CH_V2.png).

**Comment by zivillian** [comment]
> Ging damals nur über einen USB-Seriell-Adapter, der aber hier nicht mehr erforderlich zu sein scheint, da es ja bereits ein GUI gibt. Habe dort jedoch noch nicht den entsprechenden Menüpunkt gefunden.

Sobald die Firmware einma geflasht ist, gibt es einen Menüpunkt "Firmware Update"
![grafik](https://github.com/user-attachments/assets/3b94e52f-55f0-4efb-8e3a-001f5a3d8b6e)
Da können dann die fertigen Binaries hochgeladen werden

**Comment by fnsolar** [comment]
Ok, danke! Das hilft schon mal sehr weiter. Zwei Fragen noch:
- liege ich richtig, dass ich IO1 mit RX und IO3 mit TX des seriellen Adapters verbinden?
- muß ich vor dem Flashen noch NRST kurz mit GND verbinden oder irgendeinen Knopf (z.B. Factory) drücken?
Den Rest werde ich dann wohl schaffen ;-)

**Comment by fnsolar** [comment]
Habe es hinbekommen: 
- Visual Studio Code installiert und dazu PlatformIO
- IO1=TX, IO3=RX [hier](https://github.com/dtlzp/relay_dev_demo/blob/main/gpio_pinout/debug_port_2CH_V2.png)
- Vor dem Flashen IO0 kurz mit GND verbinden
- Projekt öffnen und hochladen
Werde es aber noch aufschreiben, so dass es für andere, die (wie ich) nicht im Thema stecken, nachvollziehbar wird.

**Comment by fnsolar** [comment]
**Flashen des ESP-Boards**

- Auf dem PC „Visual Studio Code“ installieren
- unter „Extensions“ (Puzzelteile-Symbol) nach „PlatformIO IDE" suchen und installieren
- „Git“ installieren [hier](https://git-scm.com/download/win)  
- Code herunterladen, entpacken und den entpackten Ordner als Projekt in PlatformIO öffnen
- Einen USB-Seriell-Adapter (z.B. [hier](https://www.beemong.com/product/ch340-usb-to-esp8266-esp-01-01s-wifi-adapter-board-module-red)) mit dem ESP verbinden (3,3V, GND, RX und TX). Das Board wird zum Flashen hierüber mit Strom versorgt. Also kein Netzteil am ESP anschliessen.
 Pinout  [hier](https://github.com/dtlzp/relay_dev_demo/blob/main/gpio_pinout/debug_port_2CH_V2.png) und [hier](https://github.com/dtlzp/relay_dev_demo/blob/main/gpio_pinout/2ch.png)  
- Programm kompilieren lassen und hochladen (in der Statusleiste von Visual Studio Code unten links der Pfeil). Abwarten bis alles hochgeladen ist.
- ESP vom USB-Adapter trennen und mit Strom versorgen. Wenn alles geklappt hat, sollte jetzt ein (neues) WLAN-Netzwerk des ESP zu sehen sein. Computer mit dem WLAN des ESP verbinden und im Browser das Webinterface des ESPs unter der IP http://192.168.4.1/ öffnen. 
- Dort die WLAN-Zugangsdaten für das eigene Heimnetz eintragen und speichern. ESP neu booten. 
- Computer wieder mit dem Heimnetz verbinden und dort den ESP suchen. Über die ihm im Heimnetz zugewiesene IP-Adresse kann nun auf die Benutzeroberfläche des ESP zugegriffen werden.
Viel Spaß!
Anmerkung: In der evcc.yaml hatt ich noch das Problem, dass unter „chargers:“ _modbus: tcpip_ stehen muss (und nicht _modbus: rs485tcpip_, wie in der automatischen Konfiguration eingetragen wurde).

PS: die Anleitung kann gerne in die Readme Datei verschoben werden, da sie dort leichter zu finden ist
